### ISSUE TITLE
случилась беда.

### ISSUE THREAD

**Issue by qazpoi12** [gerc99/SawimNE#74]
Случилась беда. Перестала заходить полседняя версия. Сейчас придется откатиться обратно, но историю скорее всего всю потеряю.

Случилось следующим образом - перестало подключаться к mail.ru серверам. После чего решил перезапустить прогу. Перезапустил - прога стала вываливаться с ошибкой. Логов никаких не вижу. Просто не запускается и все.

**Comment by gerc99** [comment]
2f53b3ed1e7d97a3c64b15f13f308b3ed52a80f3
