### ISSUE TITLE
Не подключается к gtalk

### ISSUE THREAD

**Issue by rvbglas** [gerc99/SawimNE#87]
Для эккаунта подключена двухфакторная авторизация и создан пароль приложения.

В логах:

V/SawimActivity( 2870): mEX: java.io.FileNotFoundException: https://www.google.com:443/accounts/ClientAuth?Email=*****@gmail.com&Passwd=*******&PersistentCookie=false&source=googletalk

Если URL скормить браузеру, отображается строчка:

https://developers.google.com/accounts/docs/AuthForInstalledApps

В заголовках:

HTTP/1.1 404 Not Found
Content-Type: text/plain
X-Frame-Options: DENY
Cache-control: no-cache, no-store
Pragma: no-cache
Expires: Mon, 01-Jan-1990 00:00:00 GMT
Content-Length: 65
Date: Thu, 08 Oct 2015 21:41:22 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Server: GSE
Alternate-Protocol: 443:quic,p=1
Alt-Svc: quic="www.google.com:443"; p="1"; ma=600,quic=":443"; p="1"; ma=600

По всей видимости, используется устаревший интерфейс авторизации?

**Comment by vitalyster** [comment]
По всей видимости используется устаревшая сборка из google play - это давно исправлено

**Comment by rvbglas** [comment]
Со сборкой 1.3.6(38) ругань поменялась, но работать не стало:

I/System.out(26490): connect
I/System.out(26490): host: talk.google.com
I/System.out(26490): starttls
I/System.out(26490): startTls start Socket[address=talk.google.com/74.125.205.125,port=5222,localPort=37231]java.net.PlainSocketImpl$PlainSocketOutputStream@28654ccfjava.net.PlainSocketImpl$PlainSocketInputStream@7a2f65c
I/System.out(26490): The Certificates used by peer
I/System.out(26490): CN=gmail.com, O=Google Inc, L=Mountain View, ST=California, C=US
I/System.out(26490): CN=Google Internet Authority G2, O=Google Inc, C=US
I/System.out(26490): CN=GeoTrust Global CA, O=GeoTrust Inc., C=US
I/System.out(26490): Peer host is gmail.com
I/System.out(26490): Cipher is TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
I/System.out(26490): Protocol is TLSv1.2
I/System.out(26490): ID is 32
I/System.out(26490): Session created in 1444376348000
I/System.out(26490): Session accessed in 1444377551954
I/System.out(26490): Session valid in true
I/System.out(26490): startTls done SSL socket over Socket[address=talk.google.com/74.125.205.125,port=5222,localPort=37231]com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream@e9b1d65com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream@1c1e7a3a
I/System.out(26490): tls turn on
I/System.out(26490): [INFO-JABBER] Using X-GOOGLE-TOKEN
I/System.out(26490): [INFO-JABBER] Connecting to www.google.com
I/System.out(26490): process exception: Неверный пароль (111.1)

Использую пароль приложения, с которым pidgin подключается без проблем.

**Comment by rvbglas** [comment]
С 55-й сборкой заработало.

Обновления в GooglePlay (или попадания, скажем, в F-Droid) ждать стоит?

**Comment by vitalyster** [comment]
Новые сборки недостаточно стабильны для релиза

**Comment by gerc99** [comment]
https://github.com/gerc99/SawimNE/pull/119
